"""Add generation_status enum and column

Revision ID: 9d17c043476a
Revises: 18fe05047862
Create Date: 2025-07-02 03:29:58.639488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d17c043476a'
down_revision: Union[str, None] = '18fe05047862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the GenerationStatus enum type first
    generation_status_enum = sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='generationstatus')
    generation_status_enum.create(op.get_bind())
    
    # Now add the column using the enum
    op.add_column('songs', sa.Column('generation_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='generationstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'generation_status')
    
    # Drop the enum type
    sa.Enum(name='generationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
